### PR TITLE
Rulespage

### PR DESCRIPTION
**Pull request by speckworks**
Was up Peoples!  I removed the "return home" button at the bottom of the screen.  I'm still not encountering the "invalid props" error on my branch that @oneilsw experienced.  I'm guessing its an iOS thing and since I'm not running an ios emulator, that's a hard one for me to debug.

### CODE REVIEW

**Comment by speckworks** [comment]
Ok @oneilsw I imported the <BackgroundImage> component from React Native. This Beautiful Parchment Paper should be ready to roll out (and/or scrap as the theming evolves).

**Comment by oneilsw** [comment]
LGTM

**Comment by jfeng530** [comment]
Screen Shot 2020-05-08 at 5 21 20 PM
On the IPhone, especially with certain phone sizes, the words cut off on the edges. Perhaps we could include margins to make sure the rules are being displayed properly.

**Comment by speckworks** [comment]
Yes, of course!  Let's get some theme styles going for the whole app, no?
 Rules page can be styled from style.js. I'll get on it.

**Pull request merged**
