### PR TITLE
reusable button

### PR DESCRIPTION
**Pull request by aibek1392**
Created Reusable button 
 ISSUE #29

### CODE REVIEW

**Comment by oneilsw** [comment]
LGTM

**Comment by oneilsw** [comment]
Also, the unnecessary code in Lobby.js was removed.

**Comment by jfeng530** [comment]
> Just need to rebase from master, other then that LGTM!

Should be rebased. Someone double-check one more time to make sure everything looks okay and that changes are reflected

**Comment by pavel-ilin** [comment]
We have 2 approvals from code owners! merging it with master.

**Pull request merged**
